export interface City {
  code: number;
  name: string;
  arabicName: string;
}

export const moroccanCities: City[] = [
  { code: 1, name: 'AGADIR', arabicName: 'أكادير' },
  { code: 2, name: 'AL HOCEIMA', arabicName: 'الحسيمة' },
  { code: 3, name: 'AZILAL', arabicName: 'أزيلال' },
  { code: 4, name: 'BENI MELLAL', arabicName: 'بني ملال' },
  { code: 5, name: 'BEN SLIMANE', arabicName: 'بن سليمان' },
  { code: 6, name: 'BOULEMANE', arabicName: 'بولمان' },
  { code: 7, name: 'CASABLANCA', arabicName: 'الدار البيضاء' },
  { code: 8, name: 'CHEFCHAOUEN', arabicName: 'شفشاون' },
  { code: 9, name: 'EL JADIDA', arabicName: 'الجديدة' },
  { code: 10, name: 'ERRACHIDIA', arabicName: 'الراشيدية' },
  { code: 11, name: 'ESSAOUIRA', arabicName: 'الصويرة' },
  { code: 12, name: 'FES', arabicName: 'فاس' },
  { code: 13, name: 'FIGUIG', arabicName: 'فجيج' },
  { code: 14, name: 'GUELMIM', arabicName: 'كلميم' },
  { code: 15, name: 'IFRANE', arabicName: 'إفران' },
  { code: 16, name: 'KENITRA', arabicName: 'القنيطرة' },
  { code: 17, name: 'KHEMISSET', arabicName: 'الخميسات' },
  { code: 18, name: 'KHENIFRA', arabicName: 'خنيفرة' },
  { code: 19, name: 'KHOURIBGA', arabicName: 'خريبكة' },
  { code: 20, name: 'LAAYOUNE', arabicName: 'العيون' },
  { code: 21, name: 'LARACHE', arabicName: 'العرائش' },
  { code: 22, name: 'MARRAKECH', arabicName: 'مراكش' },
  { code: 23, name: 'MEKNES', arabicName: 'مكناس' },
  { code: 24, name: 'NADOR', arabicName: 'الناظور' },
  { code: 25, name: 'OUARZAZATE', arabicName: 'ورزازات' },
  { code: 26, name: 'OUJDA', arabicName: 'وجدة' },
  { code: 27, name: 'RABAT', arabicName: 'الرباط' },
  { code: 28, name: 'SAFI', arabicName: 'آسفي' },
  { code: 29, name: 'SALE', arabicName: 'سلا' },
  { code: 30, name: 'SETTAT', arabicName: 'سطات' },
  { code: 31, name: 'SIDI KACEM', arabicName: 'سيدي قاسم' },
  { code: 32, name: 'TANGIER', arabicName: 'طنجة' },
  { code: 33, name: 'TAOUNATE', arabicName: 'تاونات' },
  { code: 34, name: 'TAROUDANT', arabicName: 'تارودانت' },
  { code: 35, name: 'TATA', arabicName: 'طاطا' },
  { code: 36, name: 'TAZA', arabicName: 'تازة' },
  { code: 37, name: 'TETOUAN', arabicName: 'تطوان' },
  { code: 38, name: 'TIZNIT', arabicName: 'تيزنيت' },
  { code: 39, name: 'DAKHLA', arabicName: 'الداخلة' },
  { code: 40, name: 'SKHIRAT-TEMARA', arabicName: 'الصخيرات-تمارة' },
  { code: 41, name: 'MEDIOUNA', arabicName: 'مديونة' },
  { code: 42, name: 'NOUACEUR', arabicName: 'النواصر' },
  { code: 43, name: 'BERRECHID', arabicName: 'برشيد' },
  { code: 44, name: 'REHAMNA', arabicName: 'الرحامنة' },
  { code: 45, name: 'SIDI BENNOUR', arabicName: 'سيدي بنور' },
  { code: 46, name: 'YOUSSOUFIA', arabicName: 'اليوسفية' },
  { code: 47, name: 'FQUIH BEN SALAH', arabicName: 'الفقيه بن صالح' },
  { code: 48, name: 'MIDELT', arabicName: 'ميدلت' },
  { code: 49, name: 'TINGHIR', arabicName: 'تنغير' },
  { code: 50, name: 'ZAGORA', arabicName: 'زاكورة' },
  { code: 51, name: 'GUERCIF', arabicName: 'جرسيف' },
  { code: 52, name: 'TAOURIRT', arabicName: 'تاوريرت' },
  { code: 53, name: 'ASSA-ZAG', arabicName: 'أسا-الزاك' },
  { code: 54, name: 'ES-SEMARA', arabicName: 'السمارة' },
  { code: 55, name: 'TAN-TAN', arabicName: 'طانطان' },
  { code: 56, name: 'AOUSSERD', arabicName: 'أوسرد' },
  { code: 57, name: 'OUED ED-DAHAB', arabicName: 'وادي الذهب' },
  { code: 58, name: 'BOUJDOUR', arabicName: 'بوجدور' },
  { code: 59, name: 'CHICHAOUA', arabicName: 'شيشاوة' },
  { code: 60, name: 'KELAA DES SRAGHNA', arabicName: 'قلعة السراغنة' },
  { code: 61, name: 'DRIOUCH', arabicName: 'الدريوش' },
  { code: 62, name: 'BERKANE', arabicName: 'بركان' },
  { code: 63, name: 'JERADA', arabicName: 'جرادة' },
  { code: 64, name: 'M\'DIQ-FNIDEQ', arabicName: 'المضيق-الفنيدق' },
  { code: 65, name: 'OUEZZANE', arabicName: 'وزان' },
  { code: 66, name: 'INEZGANE-AIT MELLOUL', arabicName: 'إنزكان-أيت ملول' },
  { code: 67, name: 'CHTOUKA-AIT BAHA', arabicName: 'شتوكة-آيت باها' },
];
